version: "3"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./frontend/dist
        target: /usr/share/nginx/html
    networks:
      - default

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/deploy.jar:/app/deploy.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/kanbanboard?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@kw1
    networks:
      - default

  database:
    build: ./database
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin@kw1'
      MYSQL_ROOT_PASSWORD: 'admin@kw1'
    volumes:
      - ./database/kanbanboard.sql:/kanbanboard.sql
    networks:
      - default

networks:
  default:
    driver: bridge