version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./frontend/dist
        target: /usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/temp.jar:/temp.jar

  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin@kw1'
      MYSQL_ROOT_PASSWORD: 'admin@kw1'
    volumes:
      - ./database/kanbanboard.sql:/kanbanboard.sql